name: GeoAlerta SAT - Ejecuci칩n Autom치tica

on:
  schedule:
    # Se ejecuta cada 6 horas (Cron Syntax)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permite que lo ejecutes manualmente con un bot칩n para probar

jobs:
  vigilancia:
    runs-on: ubuntu-latest
    
    steps:
    - name: 游닌 Descargar c칩digo del repositorio
      uses: actions/checkout@v3

    - name: 游냀 Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 游닍 Instalar librer칤as
      run: |
        pip install -r requirements.txt

    - name: 游 Ejecutar GeoAlerta SAT
      env: # <--- ESTO ES LO NUEVO
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: |
        python main.py
